default_units = true             # use bundled units
warnings_as_errors = false       # treat any warning as an error
recipe_ref_check = true          # check recipe references
max_depth = 10                   # max depth to search for recipe references

[load]
units = ["./units.toml"]

# enabled extensions
# this can also be `extensions = "all"` or `extensions = "none"`
[extensions]
COMPONENT_MODIFIERS = true
COMPONENT_ALIAS = true
ADVANCED_UNITS = true
MODES = true
INLINE_QUANTITIES = true
RANGE_VALUES = true
TIMER_REQUIRES_TIME = true
INTERMEDIATE_PREPARATIONS = true
